# Generated by Django 3.0.3 on 2020-06-10 19:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_block_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_block_user',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('last_active_date', models.DateTimeField(auto_now=True)),
                ('reputation', models.IntegerField(blank=True, default=0)),
                ('password', models.CharField(max_length=100)),
                ('like_count', models.IntegerField(blank=True, default=0)),
                ('dislike_count', models.IntegerField(blank=True, default=0)),
                ('reply_count', models.IntegerField(blank=True, default=0)),
                ('description', models.CharField(default='null', max_length=200)),
                ('dp', models.ImageField(default='user.png', upload_to='profile_image')),
                ('u_relate_u', models.ManyToManyField(blank=True, through='users.User_block_user', to='users.Users')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='user_block_user',
            name='username_1',
            field=models.ForeignKey(db_column='username_1', on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='users.Users'),
        ),
        migrations.AddField(
            model_name='user_block_user',
            name='username_2',
            field=models.ForeignKey(db_column='username_2', on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='users.Users'),
        ),
        migrations.AlterUniqueTogether(
            name='user_block_user',
            unique_together={('username_1', 'username_2')},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', django.contrib.postgres.fields.jsonb.JSONField()),
                ('other_user_id', models.ForeignKey(db_column='other_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_notification_to', to='users.Users')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='my_notification', to='users.Users')),
            ],
            options={
                'db_table': 'notifications',
                'unique_together': {('user_id', 'other_user_id')},
            },
        ),
    ]
