# Generated by Django 3.0.3 on 2020-06-11 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='last_active_date',
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
