# Generated by Django 3.0.3 on 2020-05-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='g_blocks_g',
            field=models.ManyToManyField(blank=True, related_name='_group_g_blocks_g_+', through='groups.Grp_blocks_grp', to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='g_deletes_g',
            field=models.ManyToManyField(blank=True, related_name='_group_g_deletes_g_+', through='groups.Grp_deletes_grp', to='groups.Group'),
        ),
    ]
