# Generated by Django 3.0.3 on 2020-03-21 08:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dislikes',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('like_count', models.IntegerField(blank=True, default=0)),
                ('dislike_count', models.IntegerField(blank=True, default=0)),
                ('reply_count', models.IntegerField(blank=True, default=0)),
                ('txt_body', models.TextField()),
                ('r_disliked_by', models.ManyToManyField(blank=True, related_name='disliked_reply', through='discussions.Dislikes', to='users.Users')),
                ('r_liked_by', models.ManyToManyField(blank=True, related_name='liked_reply', through='discussions.Likes', to='users.Users')),
                ('r_parent_id', models.ForeignKey(blank=True, db_column='r_parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='discussions.Reply')),
            ],
            options={
                'db_table': 'reply',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('th_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('view_count', models.IntegerField(blank=True, default=0)),
                ('t_parent_id', models.ForeignKey(blank=True, db_column='t_parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='discussions.Thread')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
            options={
                'db_table': 'thread',
            },
        ),
        migrations.CreateModel(
            name='Thread_has_parent_grp',
            fields=[
                ('th_id', models.OneToOneField(db_column='th_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parent_grp', serialize=False, to='discussions.Thread')),
            ],
            options={
                'db_table': 'thread_has_parent_grp',
            },
        ),
        migrations.AddField(
            model_name='likes',
            name='reply_id',
            field=models.ForeignKey(db_column='reply_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='liked_by', to='discussions.Reply'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='users.Users'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_id', models.IntegerField(primary_key=True, serialize=False)),
                ('link_to_img', models.CharField(max_length=100)),
                ('reply_id', models.ForeignKey(blank=True, db_column='reply_id', on_delete=django.db.models.deletion.CASCADE, related_name='related_img', to='discussions.Reply')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.AddField(
            model_name='dislikes',
            name='reply_id',
            field=models.ForeignKey(db_column='reply_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='disliked_by', to='discussions.Reply'),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='disliked', to='users.Users'),
        ),
        migrations.CreateModel(
            name='User_delete_thread',
            fields=[
                ('th_id', models.OneToOneField(db_column='th_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='thread_deleted_by', serialize=False, to='discussions.Thread')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='deleted_thread', to='users.Users')),
            ],
            options={
                'db_table': 'user_delete_thread',
            },
        ),
        migrations.CreateModel(
            name='User_delete_reply',
            fields=[
                ('reply_id', models.OneToOneField(db_column='reply_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='reply_deleted_by', serialize=False, to='discussions.Reply')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='deleted_reply', to='users.Users')),
            ],
            options={
                'db_table': 'user_delete_reply',
            },
        ),
    ]
