# Generated by Django 3.0.3 on 2020-06-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discussions', '0001_initial'),
        ('users', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='t_parent_grp',
            field=models.ForeignKey(blank=True, db_column='t_parent_grp', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_thread', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='thread',
            name='t_parent_t',
            field=models.ForeignKey(blank=True, db_column='t_parent_t', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_thread', to='discussions.Thread'),
        ),
        migrations.AddField(
            model_name='reply',
            name='r_creator',
            field=models.ForeignKey(blank=True, db_column='r_creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reply', to='users.Users'),
        ),
        migrations.AddField(
            model_name='reply',
            name='r_disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_reply', through='discussions.Dislikes', to='users.Users'),
        ),
        migrations.AddField(
            model_name='reply',
            name='r_liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_reply', through='discussions.Likes', to='users.Users'),
        ),
        migrations.AddField(
            model_name='reply',
            name='r_parent_id',
            field=models.ForeignKey(blank=True, db_column='r_parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='discussions.Reply'),
        ),
        migrations.AddField(
            model_name='likes',
            name='reply_id',
            field=models.ForeignKey(db_column='reply_id', on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='discussions.Reply'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='users.Users'),
        ),
        migrations.AddField(
            model_name='image',
            name='reply_id',
            field=models.ForeignKey(blank=True, db_column='reply_id', on_delete=django.db.models.deletion.CASCADE, related_name='related_img', to='discussions.Reply'),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='reply_id',
            field=models.ForeignKey(db_column='reply_id', on_delete=django.db.models.deletion.CASCADE, related_name='disliked_by', to='discussions.Reply'),
        ),
        migrations.AddField(
            model_name='dislikes',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='disliked', to='users.Users'),
        ),
        migrations.AddField(
            model_name='user_delete_reply',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_reply', to='users.Users'),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user_id', 'reply_id')},
        ),
        migrations.AddField(
            model_name='grp_closes_thread',
            name='grp_id',
            field=models.ForeignKey(blank=True, db_column='grp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_thread', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='group_closes_reply',
            name='grp_id',
            field=models.ForeignKey(blank=True, db_column='grp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_reply', to='groups.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='dislikes',
            unique_together={('user_id', 'reply_id')},
        ),
    ]
