# Generated by Django 3.0.3 on 2020-03-21 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discussions', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread_has_parent_grp',
            name='grp_id',
            field=models.ForeignKey(db_column='grp_id', on_delete=django.db.models.deletion.CASCADE, related_name='child_thread', to='groups.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user_id', 'reply_id')},
        ),
        migrations.AlterUniqueTogether(
            name='dislikes',
            unique_together={('user_id', 'reply_id')},
        ),
    ]
